import { eventBus } from './MissionEventBus';
import { TelemetryValidator } from './TelemetryValidator';
import { useMissionStore } from '../store/missionStore';
import type { Telemetry } from '../types/mission';

class TelemetryEngine {
  private mode: 'simulation' | 'live' = 'simulation';

  constructor() {
    eventBus.subscribe('CLOCK_TICK', this.onTick);
  }

  setMode(mode: 'simulation' | 'live') {
    this.mode = mode;
  }

  // Called when raw telemetry is received (e.g. from websocket in live mode)
  ingestLiveTelemetry(rawTelemetry: any) {
    if (this.mode !== 'live') return;
    
    if (TelemetryValidator.validate(rawTelemetry)) {
      const store = useMissionStore.getState();
      store.pushTelemetry(rawTelemetry);
      eventBus.publish('TELEMETRY_UPDATE', rawTelemetry);
    }
  }

  private onTick = (payload: { simDelta: number, tickCount: number }) => {
    if (this.mode !== 'simulation') return;
    // Simulation telemetry is generated by the MissionSimulationEngine and passed to the store
    // This engine acts as the gatekeeper
  };
}

export const telemetryEngine = new TelemetryEngine();
